import type { ExperienceSetting,ExperienceSettingValue } from '@hooksjam/gl-game-lab-engine';
export type OrbitalShrapnelConfig=Readonly<Record<string,ExperienceSettingValue>>;
export const ORBITAL_SHRAPNEL_SETTINGS:readonly ExperienceSetting[]=Object.freeze([
 n('gravity','Planet Gravity','Planet',600,3200,50,1850),n('planetRadius','Planet Radius','Planet',22,92,2,46),n('trailFade','Trail Persistence','Rendering',0,.995,.005,.972),n('debrisSize','Debris Size','Rendering',.05,2.4,.05,.72),n('debrisOpacity','Debris Opacity','Rendering',0,1,.01,1),
 {key:'starField',label:'Star Field',section:'Rendering',type:'boolean',default:true},n('starFieldOpacity','Star Opacity','Rendering',0,1,.01,.42),n('addDebrisVolume','Add Volume','Input Mode',.005,.12,.005,.035,['add']),n('addRadius','Add Radius','Input Mode',2,220,1,32,['add']),n('addDebrisVelocity','Motion Inheritance','Input Mode',0,1.4,.05,.35,['add']),n('addJitter','Add Jitter','Input Mode',0,1.5,.025,.12,['add']),n('interactionRadius','Interaction Radius','Input Mode',16,240,2,56,['interact']),n('interactionStrength','Interaction Strength','Input Mode',.1,12,.1,3.2,['interact']),n('wellRadius','Well Size','Input Mode',16,280,2,72,['well']),n('wellStrength','Well Pull','Input Mode',.1,18,.1,5.5,['well']),n('secondaryBodyCount','Secondary Bodies','Secondary Bodies',0,8,1,3),n('secondaryBodyStrength','Body Pull','Secondary Bodies',0,1.5,.05,.35),n('secondaryBodyRadius','Max Body Orbit','Secondary Bodies',.2,1.1,.025,.72),n('secondaryBodySpeed','Body Speed','Secondary Bodies',0,1.5,.025,.25),
 {key:'rawParticleTextureSize',label:'Debris Density',section:'Rendering',type:'select',default:'192',advanced:true,options:[['64² = 4k · preview','64'],['128² = 16k · light','128'],['192² = 37k · reference','192'],['256² = 65k · safe','256'],['512² = 262k · high','512'],['768² = 590k · advanced','768'],['1024² = 1.05M · extreme','1024']].map(([label,value])=>({label:label??'',value:value??''}))},
 {...n('rawMaxSpeed','Velocity Limit','Rendering',.25,8,.05,2.3),advanced:true},{...n('bloomStrength','Glow Strength','Rendering',0,2.5,.05,1.25),advanced:true},{...n('streakStrength','Streak Length','Rendering',0,1.5,.05,.75),advanced:true},
]);
export const ORBITAL_SHRAPNEL_DEFAULTS:OrbitalShrapnelConfig=Object.freeze({...Object.fromEntries(ORBITAL_SHRAPNEL_SETTINGS.map(setting=>[setting.key,setting.default])),drag:.0016});
export function createOrbitalShrapnelConfig(values:Readonly<Record<string,ExperienceSettingValue>>={}):OrbitalShrapnelConfig{const result:Record<string,ExperienceSettingValue>={...ORBITAL_SHRAPNEL_DEFAULTS};for(const setting of ORBITAL_SHRAPNEL_SETTINGS){const value=values[setting.key]??setting.default;if(setting.type==='number'&&(typeof value!=='number'||!Number.isFinite(value)||value<setting.min||value>setting.max))throw new Error(`Orbital Shrapnel setting ${setting.key} is outside its supported range`);if(setting.type==='boolean'&&typeof value!=='boolean')throw new Error(`Orbital Shrapnel setting ${setting.key} must be boolean`);if(setting.type==='select'&&!setting.options.some(option=>option.value===value))throw new Error(`Unknown Orbital Shrapnel ${setting.label}: ${String(value)}`);result[setting.key]=value}return Object.freeze(result)}
export function orbitalNumber(config:OrbitalShrapnelConfig,key:string):number{const value=config[key];if(typeof value!=='number')throw new Error(`Orbital numeric setting is unavailable: ${key}`);return value}export function orbitalString(config:OrbitalShrapnelConfig,key:string):string{const value=config[key];if(typeof value!=='string')throw new Error(`Orbital string setting is unavailable: ${key}`);return value}export function orbitalBoolean(config:OrbitalShrapnelConfig,key:string):boolean{const value=config[key];if(typeof value!=='boolean')throw new Error(`Orbital boolean setting is unavailable: ${key}`);return value}
function n(key:string,label:string,section:string,min:number,max:number,step:number,defaultValue:number,visibleModes?:readonly string[]){return Object.freeze({key,label,section,type:'number' as const,min,max,step,default:defaultValue,...(visibleModes?{visibleModes}:{})})}
