export const ORBITAL_STEP_SHADER = `#version 300 es
precision highp float;in vec2 vUv;layout(location=0)out vec4 outPosition;layout(location=1)out vec4 outVelocity;
uniform sampler2D uPositionState;uniform sampler2D uVelocityState;uniform ivec2 uStateSize;uniform int uCapacity;uniform float uDt;uniform float uTime;uniform float uAspect;uniform float uGravity;uniform float uDamping;uniform float uMaxSpeed;uniform float uPlanetRadius;uniform float uPlanetBounce;
uniform int uBodyCount;uniform float uBodyStrength;uniform float uBodyRadius;uniform float uBodySpeed;
uniform float uSpawnActive;uniform int uSpawnStart;uniform int uSpawnCount;uniform vec2 uSpawnCenter;uniform vec2 uSpawnVelocity;uniform float uSpawnRadius;uniform float uSpawnJitter;uniform float uSpawnAsteroid;uniform float uSpawnSeed;
uniform float uPointerActive;uniform int uPointerMode;uniform vec2 uPointer;uniform vec2 uPointerVelocity;uniform float uInfluenceRadius;uniform float uInfluenceStrength;
float hash(float n){return fract(sin(n)*43758.5453);}vec2 dir(float a){return vec2(cos(a),sin(a));}
void main(){ivec2 cell=ivec2(gl_FragCoord.xy);int id=cell.y*uStateSize.x+cell.x;vec4 position=texelFetch(uPositionState,cell,0),velocity=texelFetch(uVelocityState,cell,0);if(id>=uCapacity){outPosition=position;outVelocity=velocity;return;}int relative=(id-uSpawnStart+uCapacity)%uCapacity;
if(uSpawnActive>.5&&relative<uSpawnCount){float seed=uSpawnSeed+float(relative)*1.618,angle=hash(seed)*6.2831853,radius=sqrt(hash(seed+4.0))*uSpawnRadius;position.xy=uSpawnCenter+dir(angle)*radius;position.z=uSpawnAsteroid;position.w=seed;velocity.xy=uSpawnVelocity+dir(hash(seed+8.0)*6.2831853)*uSpawnJitter;velocity.z=1.0;velocity.w=seed*17.13;}
if(velocity.z>.5){vec2 p=position.xy;float r=max(.015,length(p));vec2 acceleration=-p/(r*r*r)*uGravity*.00042;
for(int body=0;body<8;body++){if(body>=uBodyCount)break;float orbit=mix(uPlanetRadius*2.2,uBodyRadius,float(body+1)/float(max(1,uBodyCount)));float phase=uTime*uBodySpeed*(.35+float(body)*.11)+float(body)*2.399;vec2 bp=dir(phase)*orbit;vec2 delta=bp-p;float d=max(.025,length(delta));acceleration+=delta/(d*d*d)*uBodyStrength*.00022;}
if(uPointerActive>.5){vec2 delta=uPointer-p;float distance=length(delta);if(distance<uInfluenceRadius){float falloff=1.0-distance/max(.001,uInfluenceRadius);if(uPointerMode==1)acceleration+=(uPointerVelocity*.018+normalize(delta+vec2(.0001))*uInfluenceStrength*.16)*falloff;else if(uPointerMode==2)acceleration+=normalize(delta+vec2(.0001))*uInfluenceStrength*1.8*falloff;}}
velocity.xy+=acceleration*uDt;velocity.xy*=exp(-uDamping*uDt);float speed=length(velocity.xy);if(speed>uMaxSpeed)velocity.xy*=uMaxSpeed/speed;position.xy+=velocity.xy*uDt;
float nextR=length(position.xy);if(nextR<uPlanetRadius){vec2 normal=normalize(position.xy+vec2(.0001));position.xy=normal*(uPlanetRadius+.003);velocity.xy=reflect(velocity.xy,normal)*uPlanetBounce;}if(abs(position.x)>uAspect*1.35||abs(position.y)>1.35){position.xy*=-.72;}}
outPosition=position;outVelocity=velocity;}`;
export const ORBITAL_POINT_VERTEX_SHADER = `#version 300 es
precision highp float;uniform sampler2D uPositionState;uniform sampler2D uVelocityState;uniform ivec2 uStateSize;uniform int uParticleCapacity;uniform float uAspect;uniform float uPointSize;uniform float uStreakStrength;out float vSpeed;flat out float vSeed;flat out float vAsteroid;
void main(){int id=gl_VertexID;ivec2 cell=ivec2(id%uStateSize.x,id/uStateSize.x);vec4 p=texelFetch(uPositionState,cell,0),v=texelFetch(uVelocityState,cell,0);if(id>=uParticleCapacity||v.z<.5){gl_Position=vec4(2,2,0,1);gl_PointSize=0.0;vSpeed=0.0;vSeed=0.0;vAsteroid=0.0;return;}gl_Position=vec4(p.x/uAspect,p.y,0,1);float speed=length(v.xy);gl_PointSize=max(1.0,uPointSize*(p.z>.5?4.5:1.0)*(1.0+speed*uStreakStrength*.32));vSpeed=speed;vSeed=v.w;vAsteroid=p.z;}`;
export const ORBITAL_POINT_FRAGMENT_SHADER = `#version 300 es
precision highp float;in float vSpeed;flat in float vSeed;flat in float vAsteroid;out vec4 outColor;uniform vec3 uPalette[8];uniform int uPaletteCount;uniform float uOpacity;uniform float uBrightness;float hash(float n){return fract(sin(n)*43758.5453);}void main(){vec2 p=gl_PointCoord*2.0-1.0;float d=dot(p,p);if(d>1.0)discard;int index=int(floor(hash(vSeed)*float(max(1,uPaletteCount))))%max(1,uPaletteCount);vec3 color=uPalette[index];float core=exp(-d*(vAsteroid>.5?2.2:5.0));outColor=vec4(color*core*uBrightness*(1.0+min(2.0,vSpeed)*.2),smoothstep(1.0,.1,d)*uOpacity);}`;
export const ORBITAL_OVERLAY_SHADER = `#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform vec2 uResolution;uniform float uTime;uniform float uPlanetRadius;uniform vec3 uPlanetA;uniform vec3 uPlanetB;uniform vec3 uPlanetLight;uniform float uStars;uniform float uStarOpacity;uniform int uBodyCount;uniform float uBodyRadius;uniform float uBodySpeed;uniform float uPointerActive;uniform int uPointerMode;uniform vec2 uPointer;uniform float uPointerRadius;
float hash(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float circle(vec2 p,vec2 c,float r){return smoothstep(r,r-.004,length(p-c));}
void main(){float aspect=uResolution.x/max(1.0,uResolution.y);vec2 p=vec2((vUv.x-.5)*2.0*aspect,(vUv.y-.5)*2.0);vec3 color=vec3(0);float alpha=0.0;if(uStars>.5){vec2 grid=floor(vUv*uResolution*.72);float star=smoothstep(.996,1.0,hash(grid));color+=vec3(.72,.82,1.0)*star;alpha=max(alpha,star*uStarOpacity);}
float planet=circle(p,vec2(0),uPlanetRadius);if(planet>0.0){float sphere=sqrt(max(0.0,1.0-dot(p,p)/(uPlanetRadius*uPlanetRadius)));float continents=smoothstep(.42,.62,hash(floor((p+vec2(uTime*.012,0))*85.0)));vec3 surface=mix(uPlanetA,uPlanetB,continents);surface*=.32+.68*max(0.0,dot(normalize(vec3(p/uPlanetRadius,sphere)),normalize(vec3(-.4,.5,1.0))));color=mix(color,surface+uPlanetLight*pow(1.0-sphere,3.0)*.35,planet);alpha=max(alpha,planet);}
for(int body=0;body<8;body++){if(body>=uBodyCount)break;float orbit=mix(uPlanetRadius*2.2,uBodyRadius,float(body+1)/float(max(1,uBodyCount)));float phase=uTime*uBodySpeed*(.35+float(body)*.11)+float(body)*2.399;vec2 bp=vec2(cos(phase),sin(phase))*orbit;float moon=circle(p,bp,uPlanetRadius*.12);color=mix(color,mix(uPlanetLight,uPlanetB,.4),moon);alpha=max(alpha,moon);}
if(uPointerActive>.5){float ring=smoothstep(.008,.001,abs(length(p-uPointer)-uPointerRadius));vec3 ringColor=uPointerMode==2?uPlanetLight:uPlanetB;color=mix(color,ringColor,ring*.7);alpha=max(alpha,ring*.7);}outColor=vec4(color,alpha);}`;
