export {
  GameEngine,
  GAME_ENGINE_RUNTIME_PLUGIN_ID,
  type GameEngineOptions,
} from './GameEngine.js';
export {
  EngineAssets,
  EngineDiagnosticsService,
  EngineQuality,
  EngineAccessibility,
  EngineAudio,
  EngineEvents,
  EngineHierarchy,
  EngineInput,
  EngineInputSources,
  EngineRenderer,
  EngineRender2D,
  EngineGpu2D,
  EngineParticleEffects,
  EngineSchedule,
  EngineScenes,
  EngineSchemas,
  EngineSerializer,
  EngineStorage,
  EngineWorkers,
  EngineWorld,
  type RenderBackend,
  type RenderBackendApi,
  type RenderBackendCapabilities,
  type RenderBackendState,
  type RenderViewport,
  type AccessibilityPoliteness,
  type AccessibilityService,
  type AudioPlaybackOptions,
  type AudioService,
  type AudioVoice,
  type PlatformServiceState,
  type StorageService,
  type StoredValue,
  type WorkerService,
  type WorkerTaskOptions,
} from './Services.js';
export {
  DEFAULT_PERFORMANCE_BUDGETS,
  EngineDiagnostics,
  type EngineDiagnosticsSnapshot,
  type PerformanceBudget,
  type PerformanceBudgetResult,
  type PerformanceTier,
  type RendererDiagnostics,
  type SystemTimingSample,
} from './Diagnostics.js';
export { AdaptiveQualityService, type QualitySnapshot } from './Quality.js';
export {
  Camera2DComponent,
  DEFAULT_FONT_2D_ID,
  Sprite2DComponent,
  SpriteAnimation2DComponent,
  Text2DComponent,
  advanceSpriteAnimations,
  createCamera2D,
  createSprite2D,
  createSpriteAnimation2D,
  createText2D,
  extractSprite2D,
  type BlendMode2D,
  type Backdrop2DOptions,
  type BitmapFont2DHandle,
  type Bloom2DOptions,
  type Camera2D,
  type Camera2DState,
  type ColorRgba,
  type Render2DService,
  type ParticleBatch2D,
  type SegmentBatch2D,
  type TriangleMeshBatch2D,
  type MetaballBatch2D,
  type FullscreenShaderEffect2D,
  type ShaderUniform2D,
  type FluidDisplay2DOptions,
  type FluidField2D,
  type FluidFieldCreate2DOptions,
  type FluidSeed2DOptions,
  type FluidSplat2D,
  type FluidStep2DOptions,
  type Sprite2D,
  type Sprite2DDraw,
  type SpriteAnimation2D,
  type Text2D,
  type Text2DDraw,
  type Texture2DHandle,
  type UvRect,
} from './Render2D.js';
export {
  InteractionRadiusIndicator2D,
  type InteractionIndicatorPointer2D,
  type InteractionRadiusIndicator2DOptions,
} from './InteractionRadiusIndicator2D.js';
export {
  applyPaletteGradientBackdrop2D,
  paletteGradientColorRgba,
  DEFAULT_PALETTE_GRADIENT_BLEND_STRENGTH,
  DEFAULT_PALETTE_GRADIENT_TIER,
  type PaletteGradientBackdrop2DOptions,
} from './PaletteGradientBackdrop2D.js';
export { InputSourceRegistry, type InputSource } from './InputSourceRegistry.js';
export {
  type Gpu2DCapabilities,
  type FluidColorMode2D,
  type Gpu2DService,
  type GpuFieldSystem2D,
  type GpuFieldSystem2DOptions,
  type GpuFieldMesh2D,
  type GpuParticleGridCapabilities2D,
  type GpuParticleGridEmit2D,
  type GpuParticleGridMetaballOptions2D,
  type GpuParticleGridObstacles2D,
  type GpuParticleGridPointOptions2D,
  type GpuParticleGridSeed2D,
  type GpuParticleGridSnapshot2D,
  type GpuParticleGridParticleUpdateOptions2D,
  type GpuParticleGridSystem2D,
  type GpuParticleGridSystem2DOptions,
  type GpuParticleGridTransfer2D,
  type GpuParticleGridTransferOptions2D,
  type GpuParticleGridUpdate2D,
  type GpuParticleGridUpdateOptions2D,
  type GpuParticleGridValidation2D,
  type GpuParticleSeed2D,
  type GpuParticleCommandBatch2D,
  type GpuParticleSystemDiagnostics2D,
  type GpuParticleSystem2D,
  type GpuParticleSystem2DOptions,
  type GpuRenderTarget2D,
  type GpuTexture2D,
  type GpuUniform2D,
  type GpuUniformBinder2D,
  type GpuUniformEncoder2D,
  type GpuUniformLocation2D,
  type GpuUniformLookup2D,
  type GpuUniforms2D,
} from './Gpu2D.js';
export {
  PARTICLE_EFFECT_COMMAND_CAPACITY,
  PARTICLE_EFFECT_STATE_ABI_VERSION,
  PARTICLE_EFFECT_STATE_LAYOUT,
  ParticleCommandQueue2D,
  particleSpawnShapeCode2D,
  resolveParticleRenderRecipe2D,
  validateParticleSettingBindings2D,
  validateParticleEffectDefinition2D,
  type ParticleAppearanceProfile2D,
  type ParticleArchetype2D,
  type ParticleBlendMode2D,
  type ParticleCapacityPolicy2D,
  type ParticleCollisionProfile2D,
  type ParticleEffectController2D,
  type ParticleEffectDefinition2D,
  type ParticleEffectDiagnostics2D,
  type ParticleEffectParameters2D,
  type ParticleEventEmitter2D,
  type ParticleEventTrigger2D,
  type ParticleLifecycleProfile2D,
  type ParticleModuleSet2D,
  type ParticleMotionProfile2D,
  type ParticlePalette2D,
  type ParticleRenderRecipe2D,
  type ParticleRenderRecipeSet2D,
  type ParticleRenderTier2D,
  type ParticleScalarCurve2D,
  type ParticleSettingBinding2D,
  type ParticleSettingValue2D,
  type ParticleSpawnCommand2D,
  type ParticleSpawnProfile2D,
  type ParticleSpawnShape2D,
} from './ParticleEffects2D.js';
export {
  PARTICLE_EFFECT_COMPILER_VERSION,
  PARTICLE_EFFECT_GRAPH_SCHEMA_VERSION,
  adaptParticleEffectDefinition2D,
  compileParticleEffect2D,
  defineParticleEffect2D,
  emitter2D,
  particleConstant2D,
  particleGraph2D,
  particleOnce2D,
  particleParameter2D,
  particleRandom2D,
  particleRate2D,
  validateParticleEffectGraph2D,
  hashParticleGraph2D,
  type CompiledParticleEffect2D,
  type ParticleCondition2D,
  type ParticleArchetypeCapacity2D,
  type ParticleBackendFallbackPolicy2D,
  type ParticleBackendRequirements2D,
  type ParticleCoordinateSpace2D,
  type ParticleCurve2D,
  type ParticleCurveKey2D,
  type ParticleEffectCompileReport2D,
  type ParticleEffectGraph2D,
  type ParticleEmitterBurst2D,
  type ParticleEmitterDefinition2D,
  type ParticleEmitterGraph2D,
  type ParticleEmitterGraphNode2D,
  type ParticleEmitterImportance2D,
  type ParticleEmitterLimits2D,
  type ParticleEmitterStopMode2D,
  type ParticleEmitterTimeline2D,
  type ParticleGraphEvent2D,
  type ParticleGraphInstruction2D,
  type ParticleInheritancePolicy2D,
  type ParticleInitialization2D,
  type ParticleInterpolation2D,
  type ParticleParameterBinding2D,
  type ParticleParameterDefinition2D,
  type ParticleParameterKind2D,
  type ParticleParameterValue2D,
  type ParticlePersistedSettingBinding2D,
  type ParticleOverflowPolicy2D,
  type ParticleQualityPolicy2D,
  type ParticleSpawnSource2D,
  type ParticleTransformPolicy2D,
  type ParticleValueSource2D,
} from './ParticleEffectGraph2D.js';
export {
  ParticleEffectLibrary2D,
  effectReferences2D,
  parseParticleEffect2D,
  resolveParticleParameters2D,
  serializeParticleEffect2D,
  type ParticleEffectAsset2D,
  type ParticleEffectLibraryDiagnostics2D,
} from './ParticleEffectAuthoring2D.js';
export {
  compileParticleProgram2D,
  validateParticleShaderBindings2D,
  type CompiledParticleProgram2D,
  type CompiledParticleRenderPass2D,
  type ParticleCompiledShader2D,
  type ParticleModuleCompilerExtension2D,
  type ParticleShaderBackend2D,
  type ParticleShaderBinding2D,
  type ParticleShaderReflection2D,
  type ParticleShaderStage2D,
} from './ParticleEffectCompiler2D.js';
export {
  EngineParticleEffects2D,
  type ParticleEffectBackendDiagnostics2D,
  type ParticleEffectBackendResource2D,
  type ParticleEffectInstance2D,
  type ParticleEffectInstanceOptions2D,
  type ParticleEffectInstanceState2D,
  type ParticleEffectInstanceStatus2D,
  type ParticleEffectRuntimeBackend2D,
  type ParticleEffects2D,
  type ParticleEffectsDiagnostics2D,
  type ParticleEmissionOverride2D,
  type ParticleEmissionWriter2D,
  type ParticleEmitterHandle2D,
  type ParticleRuntimeEmission2D,
  type ParticleSignalPayload2D,
  type ParticleTransform2D,
} from './ParticleEffectRuntime2D.js';
export {
  ParticleEffectBudgetController2D,
  ParticleEffectRecorder2D,
  ParticleEffectReplayPlayer2D,
  type ParticleBudgetDecision2D,
  type ParticleBudgetLimits2D,
  type ParticleEffectReplay2D,
  type ParticleReplayEvent2D,
} from './ParticleEffectTools2D.js';
export {
  ParticleGraphScheduler2D,
  type ParticleGraphSchedulerCallbacks2D,
} from './ParticleGraphScheduler2D.js';
export {
  ExperienceRegistry,
  ExperiencePreviewCycleControllerService,
  ExperienceRuntimeControllerService,
  ENGINE_TIME_SCALE_SETTING,
  type BooleanSetting,
  type ExperienceCapabilities,
  type ExperienceAttribution,
  type ExperienceDefinition,
  type ExperienceKind,
  type ExperienceLaunchOptions,
  type ExperienceLaunchProfile,
  type ExperienceMode,
  type ExperiencePhysicsDescriptor,
  type ExperiencePreviewProfile,
  type ExperiencePreviewCycleController,
  type ExperiencePreviewCycleOutcome,
  type ExperiencePreviewCycleRequest,
  type ExperienceRuntimeController,
  type ExperienceSetting,
  type ExperienceSettingValue,
  type ExperienceStyle,
  type ExperienceStyleManifest,
  type ExperienceTutorialPage,
  type NumberSetting,
  type PreviewFallbackImage,
  type PreviewGenerationMode,
  type PreviewRenderPolicy,
  type PreviewVariationConfig,
  type ResolvedPreviewLaunch,
  type SelectSetting,
  type StringSetting,
  createDefaultPreviewProfile,
  resolvePreviewLaunch,
  sanitizePreviewProfile,
  withoutEngineSettings,
  withEngineTimeScaleSetting,
} from './Experience.js';
