import type{GpuParticleRenderDestination}from'./GpuParticleRenderer.js';import type{GpuUniformLookup}from'./GpuSimulationPass.js';import type{GpuFieldState}from'./GpuFieldState.js';
export type GpuFieldUniformBinder=(gl:WebGL2RenderingContext,uniform:GpuUniformLookup)=>void;
export class GpuFieldPass{private readonly program:WebGLProgram;private readonly vao:WebGLVertexArrayObject;private readonly uniforms=new Map<string,WebGLUniformLocation|null>();private disposed=false;constructor(private readonly gl:WebGL2RenderingContext,fragmentSource:string){this.program=createProgram(gl,VERTEX_SHADER,fragmentSource);this.vao=requireValue(gl.createVertexArray(),'Unable to allocate GPU field vertex array')}
step(state:GpuFieldState,bind:GpuFieldUniformBinder=()=>undefined):void{this.draw(state,{framebuffer:state.targets.write.framebuffer,width:state.width,height:state.height},bind);state.swap()}
render(state:GpuFieldState,destination:GpuParticleRenderDestination,bind:GpuFieldUniformBinder=()=>undefined):void{this.draw(state,destination,bind)}
dispose():void{if(this.disposed)return;this.disposed=true;this.gl.deleteVertexArray(this.vao);this.gl.deleteProgram(this.program);this.uniforms.clear()}
private draw(state:GpuFieldState,destination:GpuParticleRenderDestination,bind:GpuFieldUniformBinder):void{if(this.disposed)throw new Error('GPU field pass has been disposed');const gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,destination.framebuffer??null);gl.viewport(0,0,destination.width,destination.height);gl.disable(gl.BLEND);gl.useProgram(this.program);gl.bindVertexArray(this.vao);state.targets.read.attach(0);gl.uniform1i(this.uniform('uFieldState'),0);gl.uniform2f(this.uniform('uFieldSize'),state.width,state.height);bind(gl,name=>this.uniform(name));gl.drawArrays(gl.TRIANGLES,0,3);gl.bindVertexArray(null);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}private uniform(name:string):WebGLUniformLocation|null{if(!this.uniforms.has(name))this.uniforms.set(name,this.gl.getUniformLocation(this.program,name));return this.uniforms.get(name)??null}}
function createProgram(gl:WebGL2RenderingContext,vs:string,fs:string){const vertex=compile(gl,gl.VERTEX_SHADER,vs),fragment=compile(gl,gl.FRAGMENT_SHADER,fs),program=requireValue(gl.createProgram(),'Unable to create GPU field program');try{gl.attachShader(program,vertex);gl.attachShader(program,fragment);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(`GPU field shader link failed: ${gl.getProgramInfoLog(program)??'unknown error'}`);return program}catch(error){gl.deleteProgram(program);throw error}finally{gl.deleteShader(vertex);gl.deleteShader(fragment)}}function compile(gl:WebGL2RenderingContext,type:number,source:string){const shader=requireValue(gl.createShader(type),'Unable to create GPU field shader');gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const detail=gl.getShaderInfoLog(shader)??'unknown error';gl.deleteShader(shader);throw new Error(`GPU field shader compilation failed: ${detail}`)}return shader}function requireValue<T>(value:T|null,message:string):T{if(value===null)throw new Error(message);return value}
const VERTEX_SHADER=`#version 300 es
const vec2 POSITIONS[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));out vec2 vUv;void main(){vec2 p=POSITIONS[gl_VertexID];vUv=p*.5+.5;gl_Position=vec4(p,0,1);}`;
