// Generated by scripts/compile-particle-effects.mjs before test, typecheck, and build.
// Runtime scene modules import this stable facade; production never composes shaders.
export {
  FIREWORKS_PARTICLE_PROGRAM,
  ORBITAL_SHRAPNEL_PARTICLE_PROGRAM,
  SPARKS_PARTICLE_PROGRAM,
} from './.generated/particle-programs.js';
