import type { ExperienceSetting } from '@hooksjam/gl-game-lab-engine';

type DescriptionCatalog = Readonly<Record<string, string>>;

const SHARED_DESCRIPTIONS: DescriptionCatalog = Object.freeze({
  renderStyle: 'Chooses the rendering pipeline used to draw the simulation.',
  maxParticles: 'Limits how many simulated particles can exist at once.',
  gravity: 'Controls the downward acceleration applied to simulated material.',
  interactionRadius: 'Sets the area around the pointer affected by interaction.',
  friction: 'Controls how strongly touching surfaces resist sliding.',
  solverPasses: 'Sets how many collision-solving passes run per simulation step. More passes improve stability but cost performance.',
  substeps: 'Splits each frame into smaller physics steps. More substeps improve fast-motion stability but cost performance.',
  collisionSoftness: 'Controls how gradually overlapping bodies are separated during collision solving.',
  opacity: 'Controls the overall visibility of the rendered simulation.',
  timeScale: 'Controls how quickly the simulation advances relative to real time.',
  resolution: 'Sets the simulation grid resolution. Higher values add detail but require more processing.',
  bloomStrength: 'Controls the brightness and spread of the glow around luminous areas.',
  trailFade: 'Controls how quickly persistent motion trails disappear.',
  rawParticleTextureSize: 'Sets the square GPU state-texture size and therefore the available particle capacity.',
  surfaceTension: 'Controls how strongly the material pulls itself into cohesive surfaces and droplets.',
  viscosity: 'Controls resistance to internal flow; higher values make the material move more thickly.',
  particleRadius: 'Sets the physical and visual radius of each simulation particle.',
  buildRadius: 'Sets the thickness of circles and pill-shaped obstacles created with Build input.',
  inputRadius: 'Sets the area around the pointer affected by the current input action.',
  inputForce: 'Controls the strength of forces applied by pointer input.',
  stiffness: 'Controls how strongly the simulated material resists compression.',
  restDensity: 'Sets the target density the solver tries to maintain.',
  surfaceSmoothing: 'Controls how strongly the rendered surface is smoothed across nearby particles.',
  enhancedQuality: 'Sets the internal quality of the Enhanced rendering path.',
  airDrag: 'Controls how quickly motion loses speed while travelling through the scene.',
  growthRate: 'Controls how quickly new growth advances through the simulation.',
  pruneRate: 'Controls how quickly existing growth is removed or dies back.',
  liquidFieldScale: 'Sets the resolution scale of the liquid surface field. Higher values add detail but cost GPU time.',
  liquidParticleRadius: 'Sets how large each particle appears when contributing to the liquid surface.',
  liquidFillDensity: 'Controls how densely gaps between particles are filled before reconstructing the surface.',
  liquidSplatDensity: 'Controls how strongly particles deposit density into the liquid surface field.',
  liquidSurfaceThreshold: 'Sets the density level at which the reconstructed liquid surface becomes visible.',
  liquidEdgeTightness: 'Controls how sharply the reconstructed liquid boundary follows the density field.',
  liquidEdgeSoftness: 'Controls the feathering at the outer edge of the reconstructed liquid surface.',
  liquidRefraction: 'Controls how strongly the liquid bends the appearance of the background behind it.',
  liquidGloss: 'Controls the strength of glossy highlights across the liquid surface.',
  liquidRimLighting: 'Controls the brightness of light around the liquid silhouette.',
  liquidFoamStrength: 'Controls the amount of bright foam generated around active liquid edges.',
  liquidThermalStrength: 'Controls how strongly particle temperature affects liquid color and light.',
  liquidBloomStrength: 'Controls glow contributed by the liquid surface rendering pass.',
  liquidHeatShimmer: 'Controls heat-driven distortion around hot portions of the liquid.',
  liquidDepthDiffusion: 'Controls how broadly density and color spread through the reconstructed liquid depth.',
  fluidColorMode: 'Chooses how the reconstructed liquid surface uses the active color palette.',
  fluidColorStrength: 'Controls how strongly fluid color mode affects the reconstructed liquid surface.',
});

const EXPERIENCE_DESCRIPTIONS: Readonly<Record<string, DescriptionCatalog>> = Object.freeze({
  'chain-rain': Object.freeze({
    maxNodes: 'Limits the total number of snake nodes that can exist at once.',
    nodeRadius: 'Sets the base radius of each circular node in a snake.',
    nodeVariance: 'Controls how much node size varies along each snake.',
    nodeVarianceWavelength: 'Sets the distance over which node-size variation repeats along a snake.',
    nodeVarianceRoughness: 'Controls how irregular the node-size variation is instead of forming a smooth wave.',
    chainLength: 'Sets how many connected nodes are created for each new snake.',
    constraintPasses: 'Sets how many times snake links are corrected per substep.',
    constraintStiffness: 'Controls how strongly connected snake nodes preserve their link lengths.',
    skinWidth: 'Sets how far the Enhanced skin extends beyond the underlying circular nodes.',
    skinHighlightWidth: 'Sets the width of the highlight running along the Enhanced snake skin.',
    skinHighlightStrength: 'Controls the brightness of the Enhanced skin highlight.',
    skinHighlightOpacity: 'Controls the visibility of the Enhanced skin highlight.',
    liquidRefraction: 'Controls background distortion through the Ultra liquid-skin rendering.',
    liquidThermalStrength: 'Controls color variation attributed to simulated snake depth and motion.',
  }),
  'soft-body-blob': Object.freeze({
    blobSize: 'Sets the starting radius of newly drawn or generated blobs.',
    nodeDensity: 'Controls how many border and filler nodes are used to construct each blob.',
    drawSmoothing: 'Controls how strongly hand-drawn blob outlines are smoothed before construction.',
    plasticFlow: 'Controls how readily a deformed blob adopts its new shape instead of springing back.',
    boundaryElasticity: 'Controls how much the blob membrane stretches and rebounds under force.',
    shapeRigidity: 'Scales the two-node bend constraint that preserves the blob outline. 0 disables it, 1 matches legacy behavior, and higher values make the shape more rigid.',
    membraneDamping: 'Controls how quickly vibration and wobble in the blob boundary settle.',
    areaPressure: 'Controls how strongly each blob tries to preserve its enclosed area.',
    skinSmoothing: 'Controls how smoothly the Enhanced skin follows the underlying boundary nodes.',
    fillerScale: 'Scales filler particles from 0 to 2 times the physical node radius without changing their count.',
    constraintPasses: 'Sets how many membrane and structure corrections run per substep.',
    squishiness: 'Controls how easily blobs compress and deform during contact.',
  }),
  'harmonic-sand': Object.freeze({
    baseFrequency: 'Sets the base vibration frequency used to form standing-wave patterns.',
    wavePeriod: 'Controls how quickly the vibration phase cycles over time.',
    rawParticleCount: 'Sets the number of sand particles used by the particle renderers.',
    rawParticleDensity: 'Controls how tightly sand particles pack around stable wave lines.',
    rawEmitterLimit: 'Limits how many wave sources can influence the field simultaneously.',
    rawLineSharpness: 'Controls how narrowly particles collect along nodal lines.',
    rawGlow: 'Controls the brightness of the glow around rendered sand particles.',
  }),
  mycelium: Object.freeze({
    topology: 'Chooses the cell layout used by the growth field.',
    branchChance: 'Controls how often an advancing tip creates an additional branch.',
    overwriteChance: 'Controls how often new growth can replace an already occupied neighboring cell.',
    growthClumping: 'Controls how strongly new cells prefer growing beside existing branches.',
    colorMutation: 'Controls how far a new cell color can shift from its parent branch color.',
    colorDriftFrequency: 'Controls how frequently branch color takes another step through its color walk.',
    branchColorSplit: 'Controls how much newly split branches diverge in color from their parent.',
    substrateColorBias: 'Controls how strongly the underlying substrate influences new branch colors.',
    brushRadius: 'Sets the radius of cells seeded by painting input.',
    fieldSpread: 'Controls how far growth influence spreads across neighboring cells.',
    ultraSurfaceThreshold: 'Sets how much branch density is required before the Ultra surface becomes solid.',
    ultraEdgeSoftness: 'Controls feathering around the Ultra reconstructed branch surface.',
    ultraHaloStrength: 'Controls the brightness of the glow surrounding Ultra branches.',
    ultraFiberStrength: 'Controls the visibility of fine directional fibers inside Ultra branches.',
    ultraCoreBrightness: 'Controls the brightness of dense branch cores in Ultra rendering.',
    ultraRimStrength: 'Controls edge lighting around Ultra branch silhouettes.',
    demoSeedColonies: 'Sets how many separate starter colonies are generated for previews and demos.',
    demoSeedRadius: 'Sets the spread of each starter colony generated for previews and demos.',
  }),
  'orbital-shrapnel': Object.freeze({
    planetRadius: 'Sets the collision radius of the central planet.',
    debrisSize: 'Sets the visual size of orbiting debris particles.',
    debrisOpacity: 'Controls the visibility of orbiting debris.',
    starField: 'Enables or disables the procedural background star field.',
    starFieldOpacity: 'Controls the brightness of the background stars.',
    addDebrisVolume: 'Sets how many debris particles Add input creates each time.',
    addRadius: 'Sets the spatial spread of debris created with Add input.',
    addJitter: 'Controls random variation in the position and velocity of newly added debris.',
    addDebrisVelocity: 'Controls the orbital launch speed assigned to newly added debris.',
    interactionStrength: 'Controls how strongly Move input pushes nearby debris.',
    wellRadius: 'Sets the area affected by a temporary gravity well.',
    wellStrength: 'Controls how strongly a temporary gravity well attracts debris.',
    secondaryBodyCount: 'Sets how many additional orbiting gravity bodies are simulated.',
    secondaryBodyStrength: 'Controls the gravitational pull of secondary bodies.',
    secondaryBodyRadius: 'Sets the visible and collision radius of secondary bodies.',
    secondaryBodySpeed: 'Controls how quickly secondary bodies orbit the central planet.',
    rawMaxSpeed: 'Caps debris velocity to prevent unstable or unreadable motion.',
    streakStrength: 'Controls how strongly fast debris stretches into motion streaks.',
  }),
  'fluid-tank': Object.freeze({
    cellSize: 'Sets the fluid-grid cell size. Smaller cells add detail but cost more GPU time.',
    curl: 'Controls vorticity confinement, which restores small swirling motion to the fluid.',
    velocityPersistence: 'Controls how much fluid velocity survives from one step to the next.',
    dyePersistence: 'Controls how slowly injected dye fades from the tank.',
    pressureIterations: 'Sets how many pressure-solving passes make the fluid incompressible.',
    ambient: 'Controls the base brightness of the fluid before directional shading.',
    shadingStrength: 'Controls how strongly dye gradients are converted into surface shading.',
    bloomThreshold: 'Sets the brightness level that begins contributing to bloom.',
    sunraysStrength: 'Controls radial light rays produced by bright dye regions.',
    fingerForce: 'Controls how strongly Stir input pushes fluid velocity.',
    fingerRadius: 'Sets the area influenced by Stir input.',
    eddyAssist: 'Adds rotational force around pointer movement to create more readable eddies.',
    injectAmount: 'Controls how much dye is added by Inject input.',
    injectTurbulence: 'Controls random curl added around newly injected dye.',
    injectPalette: 'Chooses how Inject input selects colors from the active palette.',
  }),
  'particle-fluid': Object.freeze({
    fieldCellSize: 'Sets the spacing of the background velocity field used to guide particles.',
    simulationScale: 'Scales the internal simulation domain relative to the visible canvas.',
    solverIterations: 'Sets how many incompressibility corrections run during each step.',
    cellSize: 'Sets the neighbor-search cell size used for particle interactions.',
    velocityDecay: 'Controls how quickly the guiding velocity field loses energy.',
    particleDrag: 'Controls how quickly particles match the surrounding field velocity.',
    forceRadius: 'Sets the area affected by pointer and automated flow forces.',
    forceTaper: 'Controls how sharply applied force falls off toward the edge of its radius.',
    forceStrength: 'Controls the strength of applied fluid forces.',
    pointSize: 'Sets the rendered diameter of each fluid particle.',
    pulseStrength: 'Controls the brightness of the repeating color pulse through the fluid.',
    colorSpeedScale: 'Controls how strongly particle speed shifts its rendered color.',
  }),
  'lava-lamp': Object.freeze({
    initialBlobs: 'Sets how many wax blobs are created when the lamp starts or resets.',
    blobRadius: 'Sets the base radius of newly created wax blobs.',
    buoyancy: 'Controls how strongly heated wax rises relative to cooler wax.',
    thermalDrive: 'Controls the overall strength of temperature-driven circulation.',
    heatRegion: 'Sets the height of the heated zone at the bottom of the lamp.',
    coolRegion: 'Sets the height of the cooling zone at the top of the lamp.',
    heatRate: 'Controls how quickly wax gains heat inside the bottom heating zone.',
    coolRate: 'Controls how quickly wax loses heat inside the top cooling zone.',
    heatTransfer: 'Controls how quickly neighboring wax particles exchange temperature.',
    turbulence: 'Controls the strength of slow, coherent sideways flow in the wax.',
    verticalTurbulence: 'Controls irregular vertical motion layered onto buoyant flow.',
    waxViscosity: 'Controls how strongly neighboring wax particles resist moving apart.',
    thermalContrast: 'Controls how strongly temperature changes the wax color.',
    liquidExpansion: 'Controls how much Ultra wax expands while reconstructing the surface.',
    liquidRefraction: 'Controls background distortion through Ultra wax.',
    clumping: 'Controls how strongly nearby wax particles gather into shared blobs.',
    inputLift: 'Controls the upward force applied to wax created with Add input.',
    inputThermalRate: 'Controls how hot newly added wax becomes while the pointer is held.',
    metaballBlend: 'Controls how readily nearby Basic or Enhanced blobs merge visually.',
  }),
  'water-tank': Object.freeze({
    viscositySigma: 'Controls linear viscosity between neighboring water particles.',
    viscosityBeta: 'Controls quadratic viscosity that damps larger relative velocities more strongly.',
    fluidity: 'Controls how far water particles may phase into one another and how strongly density pressure separates them. Higher values create a smoother liquid while walls and build elements remain solid.',
    supportRadiusScale: 'Sets the neighbor-interaction radius as a multiple of particle radius.',
    fluidGridResolution: 'Sets the spatial grid resolution used to find neighboring particles.',
    nearStiffness: 'Controls the extra short-range pressure that prevents particle clumping.',
    neighborPairBudget: 'Limits how many neighboring particle pairs can be processed each step.',
    collisionBounce: 'Controls restitution when water particles hit walls or built obstacles.',
    maxFluidSpeed: 'Caps particle speed to keep the solver stable during strong input.',
    obstacleRamps: 'Sets how many starter ramp obstacles appear after reset.',
    obstaclePegs: 'Sets how many starter circular pegs appear after reset.',
    pourRate: 'Controls how many water particles Pour input emits per second.',
    pourRadius: 'Sets the width of the stream created by Pour input.',
    interactionStrength: 'Controls how strongly Stir input pushes nearby water.',
    metaballBlend: 'Controls how readily nearby particles merge into the Enhanced surface.',
    fluidColorMode: 'Chooses whether Water Tank color follows the palette, particle speed, foam, or marbled variation.',
    fluidColorStrength: 'Controls how strongly Water Tank surface color uses the selected fluid color mode.',
  }),
  'splash-mpm': Object.freeze({
    particleSeparation: 'Sets the preferred spacing between visible water particles.',
    flipness: 'Blends stable PIC velocity with energetic FLIP velocity. Higher values preserve more splashing motion.',
    particleRadius: 'Sets the physical and visual radius of each Splash PIC/FLIP particle.',
    obstacleRamps: 'Sets how many randomized starter ramp obstacles appear after reset.',
    obstaclePegs: 'Sets how many randomized starter circular pegs appear after reset.',
    enhancedSplatSize: 'Sets how broadly particles deposit into the Enhanced surface field.',
    enhancedDepth: 'Controls the apparent depth and body of the Enhanced water surface.',
    enhancedEdge: 'Controls the sharpness of the Enhanced water boundary.',
    fluidColorMode: 'Chooses whether Splash color follows the palette, particle speed, foam, or marbled variation.',
    fluidColorStrength: 'Controls how strongly Splash surface color uses the selected fluid color mode.',
    emitRate: 'Controls how many water particles Pour input emits per second.',
    pourRadius: 'Sets the width of water emitted by Pour input.',
  }),
  fireworks: Object.freeze({
    launchPower: 'Controls the upward speed of newly launched firework shells.',
    launchSpread: 'Controls horizontal variation in shell launch direction.',
    shellFuse: 'Sets how long shells travel before bursting.',
    burstParticles: 'Sets how many sparks are created by each primary burst.',
    burstPattern: 'Chooses the geometric emission pattern used by primary bursts.',
    patternVariation: 'Controls how much each selected burst pattern varies without losing its recognizable shape.',
    burstChaos: 'Controls random variation in burst directions and velocities.',
    explosionPower: 'Controls the outward speed of sparks at detonation.',
    secondaryChance: 'Controls the probability that sparks create secondary bursts.',
    secondaryDepth: 'Limits how many generations of secondary bursts can occur.',
    secondaryScale: 'Controls the size and power of each successive secondary burst.',
    secondaryCount: 'Sets how many child particles each secondary event creates.',
    secondaryDelay: 'Sets the normalized age at which eligible sparks create a secondary burst.',
    secondaryInheritance: 'Controls how much parent velocity secondary sparks retain.',
    secondarySpread: 'Controls the angular variation of secondary burst particles.',
    secondaryPowerScale: 'Scales secondary burst speed relative to the primary burst.',
    terminalSparkleProbability: 'Controls the probability that a dying primary or secondary spark creates a terminal sparkle event.',
    terminalSparkleCount: 'Sets how many child particles each terminal sparkle event creates.',
    terminalSparklePower: 'Controls the outward speed of terminal sparkle particles.',
    terminalSparkleLifetime: 'Sets how long terminal sparkle particles remain visible.',
    terminalSparkleSize: 'Sets the visual size of terminal sparkle particles.',
    crackleIntensity: 'Controls flicker intensity on real terminal sparkle particles.',
    particleSize: 'Sets the base size of primary firework particles.',
    particleLength: 'Controls swept-streak length in Enhanced and Ultra rendering.',
    sparkSizeVariability: 'Controls random size variation between firework sparks.',
    paletteTransition: 'Controls how strongly sparks transition between colors from the active palette.',
    colorMode: 'Chooses whether color follows the shell, radial placement, particle age, or burst generation.',
    renderStyle: 'Chooses Basic points, Enhanced swept streaks, or Ultra trails and bloom.',
    autoFinaleRate: 'Controls how frequently automatic finale volleys launch.',
  }),
  sparks: Object.freeze({
    emissionRate: 'Controls how many primary sparks are emitted per second while drawing.',
    contactHeat: 'Controls how much heat is deposited at the active contact point.',
    sparkPower: 'Controls the initial speed of newly emitted sparks.',
    sparkDirectionChaos: 'Controls random variation in spark emission direction.',
    torchRadius: 'Sets the radius of the bright source around the pointer.',
    coreSparkTorchPositionVariability: 'Controls how far core sparks vary from the exact torch position.',
    bounceRestitution: 'Controls how much normal speed sparks retain after hitting a wall or rail.',
    bounceLifeDecay: 'Controls how much remaining spark lifetime is lost on each collision.',
    bounceBurstChance: 'Controls the probability that a collision emits an additional burst.',
    bounceBurstMinSpeed: 'Sets the minimum impact speed required to create a bounce burst.',
    bounceBurstCount: 'Sets the base number of sparks created by a bounce burst.',
    bounceBurstCountSpeedScale: 'Controls how strongly impact speed increases bounce-burst spark count.',
    bounceBurstImpactSpeedScale: 'Controls how strongly impact speed increases bounce-burst velocity.',
    bounceBurstSpread: 'Controls the angular spread of sparks created by a bounce burst.',
    sparkTurbulence: 'Controls irregular air motion applied to travelling sparks.',
    surfaceFriction: 'Controls how strongly sparks lose tangential speed when sliding along surfaces.',
    coreSparkRate: 'Controls how many bright core sparks are emitted around the source.',
    coreSparkSize: 'Sets the base size of bright core sparks.',
    coreSparkSizeVariability: 'Controls random size variation between core sparks.',
    coreSparkLifespan: 'Sets how long core sparks remain alive.',
    coreSparkLifespanVariability: 'Controls random lifetime variation between core sparks.',
    coreSparkIntensity: 'Controls the brightness of core sparks.',
    coreSparkAfterglow: 'Controls how strongly core sparks remain visible as they cool.',
    primarySparkSize: 'Sets the base width of primary sparks.',
    primarySparkSizeVariability: 'Controls random width variation between primary sparks.',
    primarySparkLength: 'Sets the base streak length of primary sparks.',
    primarySparkLengthVariability: 'Controls random streak-length variation between primary sparks.',
    primarySparkLifespan: 'Sets how long primary sparks remain alive.',
    primarySparkLifespanVariability: 'Controls random lifetime variation between primary sparks.',
    primarySparkSpeedScale: 'Scales the launch speed of primary sparks.',
    bounceSparkSize: 'Sets the base width of sparks created by collisions.',
    bounceSparkSizeVariability: 'Controls random width variation between bounce sparks.',
    bounceSparkLength: 'Sets the base streak length of bounce sparks.',
    bounceSparkLengthVariability: 'Controls random streak-length variation between bounce sparks.',
    bounceSparkLifespan: 'Sets how long bounce sparks remain alive.',
    bounceSparkLifespanVariability: 'Controls random lifetime variation between bounce sparks.',
    bounceSparkSpeedScale: 'Scales the launch speed of bounce sparks.',
    bounceSparkSpeedVariability: 'Controls random speed variation between bounce sparks.',
    trailContinuity: 'Bridges frame-to-frame gaps in fast-moving sparks without extending how long trails remain visible.',
    particleFidelity: 'Controls how many simulated particles Ultra submits to its render layers. Higher values preserve dense fine detail without changing simulation behavior.',
    trailFidelity: 'Sets the internal resolution of Ultra persistent trails. Higher values produce sharper trails at a higher GPU cost.',
    bloomThreshold: 'Sets how bright a spark must be before it contributes to Ultra bloom.',
    bloomRadius: 'Controls how far Ultra bloom spreads around bright sparks.',
    bloomFidelity: 'Sets the internal resolution of the Ultra bloom buffers. Higher values produce cleaner, less blocky glow at a higher GPU cost.',
    bloomSamples: 'Sets how many blur iterations Ultra bloom performs. More samples produce smoother glow at a higher GPU cost.',
    environmentLight: 'Controls palette-colored illumination cast onto the scene around the active spark source.',
    lightShafts: 'Controls subtle radial light beams emitted by the active spark source in Ultra rendering.',
    shaftLength: 'Controls how far Ultra light shafts extend across the scene.',
    heatDistortion: 'Controls localized animated refraction around the active hot spark source.',
    lightingFidelity: 'Sets the internal resolution of environmental light and shaft rendering. Higher values produce smoother illumination at a higher GPU cost.',
    heatRadius: 'Sets how far heat glow spreads around spark sources and impacts.',
    simDepth: 'Controls the amount of simulated depth variation used to layer sparks.',
  }),
  'turing-skin': Object.freeze({
    feedRate: 'Controls how quickly fresh activator chemical is introduced into the reaction.',
    killRate: 'Controls how quickly the reacting chemical is removed.',
    diffusionA: 'Controls how quickly the first chemical spreads across the surface.',
    diffusionB: 'Controls how quickly the second chemical spreads across the surface.',
    brushStrength: 'Controls how strongly Add or Erase input changes the reaction field.',
  }),
  'alien-vascular-tree': Object.freeze({
    branchBudget: 'Limits how many active branch tips can grow simultaneously.',
    nutrientFlow: 'Controls how strongly available nutrient guides and sustains vessel growth.',
  }),
});

export function describeSimulationSettings(
  experienceId: string,
  settings: readonly ExperienceSetting[],
): readonly ExperienceSetting[] {
  const specific = EXPERIENCE_DESCRIPTIONS[experienceId] ?? {};
  return Object.freeze(settings.map((setting) => {
    const description = setting.description?.trim() || specific[setting.key] || SHARED_DESCRIPTIONS[setting.key];
    if (!description) throw new Error(`Missing setting description for ${experienceId}.${setting.key}`);
    return Object.freeze({ ...setting, description });
  }));
}
